// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI9KpwSiTmySjQqYRsav7dXAY1b4OKuI0',
    appId: '1:1020703669703:web:66392f85c1b4b7418dede2',
    messagingSenderId: '1020703669703',
    projectId: 'flutter-starter-kit-3540e',
    authDomain: 'flutter-starter-kit-3540e.firebaseapp.com',
    storageBucket: 'flutter-starter-kit-3540e.appspot.com',
    measurementId: 'G-J77K28Y3FB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsSwHUatj9zSw6LT5wGSL9dmrazl7hIoY',
    appId: '1:1020703669703:android:45daf0082cd7decf8dede2',
    messagingSenderId: '1020703669703',
    projectId: 'flutter-starter-kit-3540e',
    storageBucket: 'flutter-starter-kit-3540e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjJ6G0rP5FIvZlNt8XcguW966N_BCzV4o',
    appId: '1:1020703669703:ios:24317ae72e27718f8dede2',
    messagingSenderId: '1020703669703',
    projectId: 'flutter-starter-kit-3540e',
    storageBucket: 'flutter-starter-kit-3540e.appspot.com',
    androidClientId: '1020703669703-eo2f670hjo127sflkias7r3vmbtg8142.apps.googleusercontent.com',
    iosClientId: '1020703669703-3rnr6a9v29uqd4onppm7d656fi4aib8l.apps.googleusercontent.com',
    iosBundleId: 'com.fsk.app',
  );
}
